version: '3.1'

services:
  account_database:
    image: postgres
    restart: always
    volumes:
      - ${HOME}/database/data:/var/lib/postgresql/data
      - ${HOME}/database/init:/docker-entrypoint-initdb.d # sql 파일을 실행시키기 위한 경로
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # default database name