spring:
  config:
    import: "configserver:${spring.cloud.config.uri}"
  cloud:
    config:
      uri: http://localhost:8888
      profile: local
      label: main
    gateway:
      routes:
        - id: account_service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**, /accounts/** , /login/**
        - id: travel_core
          uri: lb://TRAVEL-CORE
          predicates:
            - Path=/place/**, /plan/**
management:
  endpoint:
    gateway:
      enabled: true