logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    root: debug
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
  cloud:
    aws:
      s3:
        enabled: true
      region:
        static: ap-northeast-2
  config:
    import: file:${HOME}/github/Managed-Travel-Service/secret/backend/modular/application-test.yml
    #from submodule which set to private access. see {@file .gitmodules} on project root directory
google:
  api:
    key: ${GOOGLE_API_KEY}