logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    root: debug
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
  cloud:
    aws:
      s3:
        enabled: true
      region:
        static: ap-northeast-2
  config:
    import: file:${HOME}/Project/managed_travel/application-test.yml
# spring:
#  datasource:
#    url:
#    username:
#    password:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:
#  cloud:
#    aws:
#      credentials:
#        access-key:
#        secret-key:
#      s3:
#        region:
#        profile-img-bucket: