server:
  servlet:
    session:
      timeout: 60m
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  config:
    import: file:${HOME}/github/Managed-Travel-Service/secret/backend/modular/application-local.yml
    #from submodule which set to private access. see {@file .gitmodules} on project root directory