google:
  api:
    key: ${GOOGLE_API_KEY}
spring:
  graphql:
    graphiql:
      enabled: true
      path: /place/graphiql
    path: /place/graphql
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mydatabase
      username: root
      password: example
logging:
  level:
    root: debug