spring:
  graphql:
    graphiql:
      enabled: true
server:
  port: 29090
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
    use-relative-redirects: true
jwt:
  secret: ${JWT_SECRET}