logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans # refresh for cloud config refresh
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
  config:
    import: "configserver:${spring.cloud.config.uri}"
  cloud:
    config: # config server 설정
      uri: http://localhost:8888
      profile: local
      label: main
    aws:
      s3:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
