openapi: 3.0.3
info:
  title: Travel Plan API
  description: 이 문서는 여행 계획 서비스의 API 명세서입니다.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local Server(개발용)
tags:
  - name: travel
    description: 여행 계획 관련 API
paths:
  /v1/travels:
    post:
      tags:
        - travel
      summary: 여행 생성
      description: 여행을 생성합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TravelPostRequest'
      responses:
        '201':
          description: 여행 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Travel'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    get:
      tags:
        - travel
      summary: 자신의 여행 Id 목록 조회
      description: 자신의 여행 Id 목록을 조회합니다.
      responses:
        '200':
          description: 여행 조회 성공
          content:
            application/json:
              schema:
                type: array
                example: ["1dsafadsf", "fif1fdjiaj"]
                items: # 여행 id string 목록
                  type: string
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}:
    get:
      tags:
        - travel
      summary: 여행 조회
      description: 여행을 조회합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: 여행 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Travel'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    put:
      tags:
        - travel
      summary: 여행 정보 수정
      description: 여행 정보를 수정합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 여행 제목
                  example: 여행 제목
                startDate:
                  type: string
                  format: yyyy-MM-dd
                  description: 여행 시작 날짜
                  example: 2021-01-01
      responses:
        '200':
          description: 여행 정보 수정 성공
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}/days:
    get:
      tags:
        - travel
      summary: 여행 전체 경로 조회
      description: 여행 전체 경로를 조회합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: false
          schema:
            type: string
            example: "1dsafadsf"
      responses:
        '200':
          description: 여행 경로 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Day'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    post:
      tags:
        - travel
      summary: 여행 날짜 추가
      description: 여행 날짜를 추가합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      requestBody:
        required: false
        description: 바디가 없으면, 맨 뒤에 추가
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayPostRequest'
      responses:
        '201':
          description: 여행 경로 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Travel'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    put:
      tags:
        - travel
      summary: 여행 날짜 순서 변경
      description: 여행 날짜 순서를 변경합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
        - name: dayId
          in: query
          description: 변경할 날짜 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: cursor
          in: query
          description: 어떤 날짜 뒤에 추가할 것인지, NULL일 경우 맨 앞에 추가
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  dayId:
                    type: string
                    description: 날짜의 ID
                    example: saldkfjaslfdkj
                  waypoints:
                    type: array
                    items:
                      type: string
                      description: placeId
                      example: asdlfjasd21kfasjdl
              example: [{"dayId": "1", "waypoints": ["1", "2"]}, {"dayId": "2", "waypoints": ["3", "4"]}]
      responses:
        '200':
          description: 여행 날짜 순서 변경 성공
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}/days/{dayId}:
    get:
      tags:
        - travel
      summary: 특정 날짜의 경로 조회
      description: 특정 날짜의 경로를 조회합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: 1
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: 여행 경로 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    delete:
      tags:
        - travel
      summary: 날짜 삭제
      description: 날짜를 삭제합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: 1
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: 날짜 삭제 성공
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}/waypoints:
    post:
      tags:
        - travel
      summary: 추천 위치에 경유지 추가
      description: 추천 위치에 경유지를 추가합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                example: "1dsafadsf"
      responses:
        '201':
          description: 경유지 추가 성공
          content:
            application/json:
              schema:
                type: array
                description: 추가된 날짜의 경유지 목록
                items:
                  $ref: '#/components/schemas/Travel'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}/days/{dayId}/waypoints:
    get:
      tags:
        - travel
      summary: 특정 날짜의 경유지 조회
      description: 특정 날짜의 경유지를 조회합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      responses:
        '200':
          description: 여행 경로 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    post:
      tags:
        - travel
      summary: 경유지 추가
      description: 경유지를 추가합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaypointPostRequest'
      responses:
        '201':
          description: 경유지 추가 성공
          content:
            application/json:
              schema:
                type: array
                description: 추가된 날짜의 경유지 목록
                items:
                  $ref: '#/components/schemas/Day'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
  /v1/travels/{travelId}/days/{dayId}/waypoints/{waypointId}:
    get:
      tags:
        - travel
      summary: 경유지 조회
      description: 경유지를 조회합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: waypointId
          in: path
          description: 경유지 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      responses:
        '200':
          description: 경유지 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WayPoint'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    delete:
      tags:
        - travel
      summary: 경유지 삭제
      description: 경유지를 삭제합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
        - name: waypointId
          in: path
          description: 경유지 ID
          required: true
          schema:
            type: string
            example: "1dsafadsf"
      responses:
        '200':
          description: 경유지 삭제 성공
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러
    put:
      tags:
        - travel
      summary: 경유지 정보 변경
      description: 경유지 정보를 변경합니다.
      parameters:
        - name: travelId
          in: path
          description: 여행 ID
          required: true
          schema:
            type: string
        - name: dayId
          in: path
          description: 여행 일자 ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memo:
                  type: string
                  description: 메모
                  example: "메모"
                time:
                  type: string
                  format: HH:mm
                  description: 시간
                  example: "12:00"
      responses:
        '200':
          description: 경유지 정보 변경 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WayPoint'
        '400':
          description: 잘못된 요청
        '500':
          description: 서버 에러

components:
  schemas:
    TravelPostRequest:
      type: object
      properties:
        title:
          type: string
          description: 여행 제목
          required: true
          minLength: 1
          maxLength: 100
          example: 여행 제목
        dayCount:
          type: integer
          required: true
          description: 여행 일수
          example: 3
        startDate:
          type: string
          format: yyyy-MM-dd
          required: false
          description: 여행 시작 날짜
          example: 2021-01-01
        places:
          required: false
          type: array
          description: 장소 ID 목록, 최적 위치로 추가되어서 생성됩니다.
          items:
            type: string
            example: "1dsafadsf"
    WaypointPostRequest:
      type: object
      description: 특정 날짜에 경유지를 추가할 때 사용하는 요청
      properties:
        places:
          type: array
          description: 장소 ID 목록
          items:
            type: string
            example: "1dsafadsf"
        cursor:
          type: string
          required: true
          nullable: true
          description: 어떤 여행지 뒤에 추가할 것인지, NULL일 경우 맨 앞에 추가
          example: "1dsafadsf"
    DayPostRequest:
      type: object
      properties:
        cursor:
          type: string
          required: false
          nullable: true
          description: 어떤 날짜 뒤에 추가할 것인지, NULL일 경우 맨 앞에 추가
          example: "1dsafadsf"
    RouteOrderUpdateRequest:
      type: array
      items:
        type: object
        properties:
          dayId:
            type: string
            description: 날짜의 ID
            example: saldkfjaslfdkj
          waypoints:
            type: array
            items:
              type: string
              description: placeId
              example: asdlfjasd21kfasjdl

    Travel:
      type: object
      properties:
        travelId:
          type: string
          description: 여행 ID
          example: 1
        title:
          type: string
          description: 여행 제목
          example: 여행 제목
        startDate:
          type: string
          format: yyyy-MM-dd
          description: 여행 시작 날짜
          example: 2021-01-01
        days:
          type: array
          description: 여행 경로
          items:
            $ref: '#/components/schemas/Day'
    Day:
      type: object
      properties:
        dayId:
          type: string
          description: 여행 일자 ID
          example: iafi3j2
        wayPoints:
          type: array
          items:
            $ref: '#/components/schemas/WayPoint'
    WayPoint:
      type: object
      properties:
        waypointId:
          type: string
          description: 경유지
          example: a1b2c3d4
        placeId:
          type: string
          description: 장소 ID
          example: a1b2c3d4
        memo:
          type: string
          description: 메모
          example: 메모
        time:
          type: string
          format: HH:mm
          description: 시간
          example: 12:00
