logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    root: debug
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans # refresh for cloud config refresh
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
  config:
    import: "configserver:${spring.cloud.config.uri}"
  cloud:
    config: # config server 설정
      uri: http://localhost:8888
      profile: local
      label: main
    aws:
      s3:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/