server:
  port: 29091
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
    consumer:
      group-id: "test"
  config:
    import: file:${HOME}/github/Managed-Travel-Service/secret/backend/modular/application-test.yml