google:
  api:
    key: ${GOOGLE_API_KEY}
spring:
  docker:
    compose:
      file: ${PWD}/backend/travel_plan/travel_plan_service/compose.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  health:
    elasticsearch:
      enabled: false