spring:
  config:
    import: "configserver:${spring.cloud.config.uri}"
  cloud:
    config:
      uri: http://localhost:8888
      profile: local
      label: main
    gateway:
      routes:
        - id: login_service
          uri: http://localhost:29090
          predicates:
            - Path=/account/login/**, /account/register/**, /login/oauth2/code/**

        - id: account_service
          uri: http://localhost:29090
          predicates:
            - Path=/account/**, /users/**
          filters:
            - name: JwtAuthorization
              args:
                config:
                  roles: ADMIN, USER

        - id: place_service
          uri: http://localhost:29091
          predicates:
            - Path=/place/**
          filters:
            - name: JwtAuthorization
              args:
                config:
                  roles: USER, ADMIN
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, gateway # refresh for cloud config refresh
  endpoint:
    gateway:
      enabled: true