spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8080
          predicates:
            - Path=/account/**
          filters:
            - name: JwtAuthorization
              args:
                allowedRoles:
                  - ADMIN
                  - USER

