spring:
  config:
    import: "configserver:${spring.cloud.config.uri}"
  cloud:
    config:
      uri: http://localhost:8888
      profile: local
      label: main
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:29090
          predicates:
            - Path=/account/**, /users/**, /login/**
        - id: travel_core
          uri: http://localhost:29091
          predicates:
            - Path=/place/**, /plan/**
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, gateway # refresh for cloud config refresh
  endpoint:
    gateway:
      enabled: true